### PR TITLE
update branch for merge

### PR DESCRIPTION
**Pull request by LothropRO**
## Issue
Closes #<issue number>

## Description
A few sentences describing the overall goals of the pull request's commits.

## Test Plan
Describe how to test the code in your PR

## Expected Results
The output that should be expected

## Style Score
<pylint score>/10

## Bugs
Only if necessary, things that will need to be fixed in the future

## Future Plans
Where to go from here

### CODE REVIEW

**Comment by mattsmith803** [comment]
Bug: colliding after pressing "Back"
* "Create show"
* choose initial moment video
* add rule `pitch < 500`
* press "Back", press "Yes" in system dialogue to exit without saving
* "Create Show"
* choose initial moment video
* add rule `pitch < 400`, throws error `['pitch', '<', '400'] collides with rule: [['pitch', '<', '400']]`

Bug: different buttons triggering collide error
* "Create Show"
* choose initial moment
* add rule `pitch < 500`
* "Add Moment", choose video
* add rule `pitch < 400`
* "Add Moment", throws correct error, `[['pitch', '<', '400']] Collides with moment [['pitch', '<', '500']]`
* "Remove Rule"
* Populate rule boxes with `pitch < 400` again, press "Add Rule", throws error `['pitch', '<', '400'] collides with rule: [['pitch', '<', '400']]`

Not sure if this is expected? Also note the first time it throws an error its a list of lists collides with list of list where the second time its just a list collides with a list of lists.

**Comment by mattsmith803** [comment]
Also need to update to latest master branch

**Comment by aholdeman** [comment]
Omari and I are working on it now -- I should have just fixed the first error.

**Comment by aholdeman** [comment]
Should be fixed now!

**Comment by mattsmith803** [comment]
Those previous bugs seem to be fixed.

### New bugs

* "Create Show"
* choose initial moment
* add rule `pitch < 500`
* "Add Moment", choose video
* add rule `pitch < 400`

**Comment by mattsmith803** [comment]
Ignore latest comment if see in email. Accidentally pressed enter.

**Comment by aholdeman** [comment]
Ultimately, it's up to @LothropRO since it's his feature, I was just helping since we were in the same class and the program runs better on my machine.  If he thinks the above errors are easily fixable in the next 2 hours and is willing to create a more comprehensive test plan, I say go for it, else, focus on the testing milestone.

Thoughts?

**Comment by mattsmith803** [comment]
Agreed. @LothropRO do what you feel is best. I'll close this PR for now. Reopen if you decide to keep pursuing it, fix bugs, and create a comprehensive test plan.

**Pull request closed without merging**
